# data preprocessing 
# 1.data cleaning

In [1]:
import pandas as pd
import numpy as np
from faker import Faker

fake = Faker()

# Generate 100 rows of fake customer data
data = {
    "Name": [fake.name() for _ in range(100)],
    "Age": np.random.randint(18, 70, 100),
    "JoinDate": [fake.date_between(start_date="-5y", end_date="today") for _ in range(100)],
    "Email": [fake.email() for _ in range(100)],
    "PurchaseAmount": np.random.choice([100, 200, None, 500, 1000], 100)  # includes missing values
}

df = pd.DataFrame(data)

# Add duplicates and inconsistencies
df.loc[5] = df.loc[10]   # duplicate row
df.loc[20, "Age"] = None # missing value
df.loc[30, "Email"] = "not_an_email" # invalid entry

print(df.head())

                Name   Age    JoinDate                     Email  \
0   Tracy Washington  24.0  2021-09-07      ysanchez@example.org
1        Mark Barnes  47.0  2025-09-16      ianbrown@example.org
2  Elizabeth Miranda  39.0  2026-02-23      shiggins@example.org
3   Jennifer Higgins  56.0  2022-05-21      leslie71@example.net
4       Krystal Cobb  27.0  2023-08-13  alexabennett@example.com

  PurchaseAmount
0            500
1            200
2           1000
3            200
4            200

In [2]:
pd.DataFrame(df)

,Name,Age,JoinDate,Email,PurchaseAmount
0,Tracy Washington,24.0,2021-09-07,ysanchez@example.org,500
1,Mark Barnes,47.0,2025-09-16,ianbrown@example.org,200
2,Elizabeth Miranda,39.0,2026-02-23,shiggins@example.org,1000
3,Jennifer Higgins,56.0,2022-05-21,leslie71@example.net,200
4,Krystal Cobb,27.0,2023-08-13,alexabennett@example.com,200
...,...,...,...,...,...
95,Walter Joseph,50.0,2024-02-18,michelleterry@example.com,500
96,Donna King,66.0,2024-10-24,igarrett@example.com,500
97,Mark Blackwell,18.0,2025-02-12,danny04@example.org,100
98,Sarah Bell,45.0,2022-07-15,smithgerald@example.org,None
99,Jennifer Underwood,25.0,2023-02-15,smithkristin@example.com,1000

In [3]:
df.isnull().sum()

Name               0
Age                1
JoinDate           0
Email              0
PurchaseAmount    16
dtype: int64

# missing values treatement

In [4]:
df['Age'].isnull().sum()

np.int64(1)

In [5]:
df['Age']=np.mean(df['Age'])

In [6]:
df['Age'].isnull().sum()

np.int64(0)

In [7]:
df['PurchaseAmount'].isnull().sum()

np.int64(16)

In [8]:
df.isnull().sum()

Name               0
Age                0
JoinDate           0
Email              0
PurchaseAmount    16
dtype: int64

# duplicate finding

In [9]:
df.duplicated().sum()

np.int64(1)

In [10]:
df=df.drop_duplicates()

In [11]:
df.duplicated().sum()

np.int64(0)

# handling the outliers

In [12]:
df['PurchaseAmount'].mean()

np.float64(495.1807228915663)

In [13]:
df['PurchaseAmount'].max()

1000

In [14]:
df['PurchaseAmount'].min()

100

In [15]:
df['PurchaseAmount'].std()

np.float64(369.542767734449)

In [16]:
df['PurchaseAmount'].var()

np.float64(136561.8571848369)

In [17]:
mean=495.180
mx=1000
mn=100
std=369.542

zscore=(df['PurchaseAmount']-mean) / std
print(zscore)

0     0.013043
1    -0.798773
2     1.366069
3    -0.798773
4    -0.798773
        ...
95    0.013043
96    0.013043
97   -1.069378
98         NaN
99    1.366069
Name: PurchaseAmount, Length: 99, dtype: object

In [24]:
df['PurchaseAmount_zscore'] = (df['PurchaseAmount'] - df['PurchaseAmount'].mean()) / df['PurchaseAmount'].std()

In [25]:
df.head()

,Name,Age,JoinDate,Email,PurchaseAmount,PurchaseAmount_zscore
0,Tracy Washington,44.353535,2021-09-07,ysanchez@example.org,500,0.013041
1,Mark Barnes,44.353535,2025-09-16,ianbrown@example.org,200,-0.798773
2,Elizabeth Miranda,44.353535,2026-02-23,shiggins@example.org,1000,1.366065
3,Jennifer Higgins,44.353535,2022-05-21,leslie71@example.net,200,-0.798773
4,Krystal Cobb,44.353535,2023-08-13,alexabennett@example.com,200,-0.798773

# hadle the categorical data

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder(df[['Name','Email']])
le.fit_transform()